# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao', models.CharField(max_length=120)),
                ('fantasia', models.CharField(blank=True, max_length=120)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('ano_fabricacao', models.IntegerField(blank=True)),
                ('ano_modelo', models.IntegerField(blank=True)),
                ('chassi', models.CharField(blank=True, max_length=60)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Marca')),
            ],
        ),
    ]
