# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
    ]
