# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 20:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20160403_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Centro_de_custo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateField(default=datetime.date.today)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Conta')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('descricao', models.CharField(max_length=120)),
                ('emissao', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('vencimento', models.DateField(default=datetime.date.today)),
                ('tipo', models.CharField(choices=[('P', 'PAGAR'), ('R', 'RECEBER')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_juros', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Categoria')),
                ('centro_de_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Centro_de_custo')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Conta')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='produto',
            name='saldo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
