# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20160403_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.Pessoa')),
            ],
            bases=('cadastros.pessoa',),
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.Pessoa')),
            ],
            bases=('cadastros.pessoa',),
        ),
        migrations.AlterModelOptions(
            name='centro_de_custo',
            options={'verbose_name': 'Centro de Custo', 'verbose_name_plural': 'Centros de Custo'},
        ),
        migrations.AlterModelOptions(
            name='titulo',
            options={'verbose_name': 'Título', 'verbose_name_plural': 'Títulos'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
    ]
