# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20160409_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='pessoa_ptr',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
